- name: Base configuration for all hosts
  hosts: all
  roles:
    - base

- name: Proxmox common configuration
  hosts: proxmox
  roles:
    - proxmox-common

- name: Observability agents
  hosts: proxmox
  roles:
    - alloy

- name: Proxmox cluster setup
  hosts: proxmox
  serial: 1
  tags: cluster
  roles:
    - proxmox-cluster
