- name: Check if node is already in a cluster
  ansible.builtin.stat:
    path: /etc/pve/corosync.conf
  register: corosync_conf

- name: Create cluster on master
  ansible.builtin.command: pvecm create {{ pve_cluster_name }}
  when:
    - inventory_hostname == pve_cluster_master
    - not corosync_conf.stat.exists
  changed_when: true

- name: Join cluster on other nodes
  ansible.builtin.command: pvecm add {{ pve_cluster_master }}
  when:
    - inventory_hostname != pve_cluster_master
    - not corosync_conf.stat.exists
  changed_when: true
