- name: Check if node is already in a cluster
  ansible.builtin.command: pvecm status
  register: pvecm_status
  changed_when: false
  failed_when: false

- name: Create cluster on master
  ansible.builtin.command: pvecm create {{ pve_cluster_name }}
  when:
    - inventory_hostname == pve_cluster_master
    - pvecm_status.rc != 0
  changed_when: true

- name: Join cluster on other nodes
  ansible.builtin.command: pvecm add {{ pve_cluster_master }}
  when:
    - inventory_hostname != pve_cluster_master
    - pvecm_status.rc != 0
  changed_when: true
