- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    state: restarted

- name: Reload systemd for AER units
  ansible.builtin.systemd:
    daemon_reload: true
