all:
  children:
    proxmox:
      children:
        m75q:
          hosts:
            pve01.home.arpa:
            pve02.home.arpa:
            pve03.home.arpa:
            pve04.home.arpa:
        ed800g9:
          hosts:
            pve05.home.arpa:
