pve_admin_user: noah
pve_admin_ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIJhzSG7KoFZGQItZr1p48xcZ9ZHwlM0kzEH8tvZLxIi noah@proxmox"
pve_no_subscription_repo: "deb http://download.proxmox.com/debian/pve trixie pve-no-subscription"
pve_enterprise_sources:
  - /etc/apt/sources.list.d/pve-enterprise.sources
  - /etc/apt/sources.list.d/pve-enterprise.list
  - /etc/apt/sources.list.d/ceph.sources
